# fly.toml app configuration file generated for jetzig-website-smtp on 2025-04-21T13:17:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jetzig-website-smtp'
primary_region = 'ams'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
